/**
 * generated by Xtext 2.26.0
 */
package dk.sdu.mmmi.mdsd.math;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Function Use</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see dk.sdu.mmmi.mdsd.math.MathPackage#getFunctionUse()
 * @model
 * @generated
 */
public interface FunctionUse extends Expression
{
} // FunctionUse
